# Generated by Django 5.0.2 on 2024-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxhome', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
