# Generated by Django 5.0.2 on 2024-02-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxhome', '0004_customusermanager_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='reenter',
            new_name='confirm_password',
        ),
    ]
