# Generated by Django 5.0.2 on 2024-02-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxhome', '0005_rename_reenter_userregister_confirm_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserManager',
        ),
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=200),
        ),
    ]
