# Generated by Django 5.0.2 on 2024-03-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxhome', '0008_product3_product4_product5_product6_product7_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product3',
            name='Catagories',
        ),
        migrations.RemoveField(
            model_name='product4',
            name='Catagories',
        ),
        migrations.RemoveField(
            model_name='product5',
            name='Catagories',
        ),
        migrations.RemoveField(
            model_name='product6',
            name='Catagories',
        ),
        migrations.RemoveField(
            model_name='product7',
            name='Catagories',
        ),
        migrations.RemoveField(
            model_name='product8',
            name='Catagories',
        ),
        migrations.RemoveField(
            model_name='products2',
            name='Catagories',
        ),
    ]
