# Generated by Django 5.0.2 on 2024-03-01 10:55

import maxhome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxhome', '0009_remove_product3_catagories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Vendor', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=maxhome.models.getfilename)),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='products2',
            new_name='accessories',
        ),
        migrations.RenameModel(
            old_name='product3',
            new_name='Fashions',
        ),
        migrations.RenameModel(
            old_name='product4',
            new_name='HomeAppliences',
        ),
        migrations.RenameModel(
            old_name='product6',
            new_name='NutritionsandMore',
        ),
        migrations.RenameModel(
            old_name='product7',
            new_name='shoesandcheppals',
        ),
        migrations.RenameModel(
            old_name='product5',
            new_name='sports',
        ),
        migrations.RenameModel(
            old_name='product8',
            new_name='Toys',
        ),
        migrations.RenameModel(
            old_name='catagories',
            new_name='Trendings',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
